// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwv_RBCgmq2sViyhLmLwL0GYgoDGW2VUw',
    appId: '1:470702893457:web:ef252b16f18c664efd5230',
    messagingSenderId: '470702893457',
    projectId: 'aizle-check',
    authDomain: 'aizle-check.firebaseapp.com',
    storageBucket: 'aizle-check.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCywXJs4jcIzrXyGUSbBdbNPWSD8V85TaA',
    appId: '1:470702893457:android:b8f9dd8e55b1f775fd5230',
    messagingSenderId: '470702893457',
    projectId: 'aizle-check',
    storageBucket: 'aizle-check.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMEv5xu-NPnuP_wOjjB9Cg2UhIbSqk88U',
    appId: '1:470702893457:ios:c833dfc65d092dcbfd5230',
    messagingSenderId: '470702893457',
    projectId: 'aizle-check',
    storageBucket: 'aizle-check.appspot.com',
    iosBundleId: 'com.aislecheck.www.aislecheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMEv5xu-NPnuP_wOjjB9Cg2UhIbSqk88U',
    appId: '1:470702893457:ios:c661bcce36fce793fd5230',
    messagingSenderId: '470702893457',
    projectId: 'aizle-check',
    storageBucket: 'aizle-check.appspot.com',
    iosBundleId: 'com.example.aizlecheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwv_RBCgmq2sViyhLmLwL0GYgoDGW2VUw',
    appId: '1:470702893457:web:d6de513243764d7efd5230',
    messagingSenderId: '470702893457',
    projectId: 'aizle-check',
    authDomain: 'aizle-check.firebaseapp.com',
    storageBucket: 'aizle-check.appspot.com',
  );
}
